### PR TITLE
Update package structure for compatibility with future rstan

### PR DESCRIPTION
**Pull request by andrjohns**
This PR updates your package's structure to fully delegate to `rstantools` for installation, to help ensure compatibility with future versions of `rstan`.

I've included a modification to the `configure.win` script to skip the model compilation on 32-bit windows, and also made a minor update to the `cov.stan` model to workaround a bug in Stan 2.31

Let me know if you have any questions/clarifications. Thanks!

### CODE REVIEW

**Comment by cdriveraus** [comment]
Thanks, but still tries to compile on 32 bit:
https://win-builder.r-project.org/lam00pUh4l9n/00install.out

**Comment by andrjohns** [comment]
Ah figured it out. It worked locally because R would only configure and build for the current architecture. When submitting to winbuilder, it looks like it configures for 64bit and then builds for both (equivalent to adding the `Biarch: true` flag to the `DESCRIPTION`. Rather than figuring out some makevars/configure trickery to ignore the sources on 32-bit, I've opted to instead add a compiler flag to reduce memory usage during compilation (at the cost of increased compile times) which allows the package to build under 32-bit

**Comment by cdriveraus** [comment]
ok interesting. Usually CRAN seems to hate playing with compiler flags but I think you have more familiarity in this regard so I'll try and see. ctsem already seems pretty borderline on their timeouts, but maybe if it's just to get by on the oldrelease it will be fine.

**Comment by cdriveraus** [comment]
Still out of memory: 
https://win-builder.r-project.org/GmLJ7xO4qx51/00install.out

**Comment by andrjohns** [comment]
That log doesn't have the new flag (`--param ggc-min-expand=10`), and I've confirmed that it builds fully under 32-bit locally. Any chance that an old version was uploaded or similar?

**Comment by cdriveraus** [comment]
just double checked my upload, it has the updated configure.win. I've occasionally had weird problems with cached / old packaged uploads on winbuilder though, will try again with an updated version...

**Comment by cdriveraus** [comment]
nope
https://win-builder.r-project.org/C6e3X5KPNrnm/00install.out

**Comment by cdriveraus** [comment]
[ctsem_3.7.5.tar.gz](https://github.com/cdriveraus/ctsem/files/11027774/ctsem_3.7.5.tar.gz)
Here is the uploaded package

**Comment by andrjohns** [comment]
The configure.win script in that package has a typo: `>> src/Makevars.wi` (`.wi` instead of `.win`)

**Comment by andrjohns** [comment]
For that you could either have a message to CRAN that the sources are generated on install, or you could try having a `src` folder with just the [rstantools Makevars files](https://github.com/stan-dev/rstantools/tree/master/inst/include/sys) which should get automatically replaced on installation

**Comment by cdriveraus** [comment]
Needed a real source file in the src folder, so left RcppExports.cpp, now it works. Thanks for your help on this.

**Pull request closed without merging**
